### ISSUE TITLE
Improve the css and Add dark mode and add message on focus change.

### ISSUE THREAD

**Issue by kaal-coder** [CareerDevelopmentHub/Sudoku-Solver#1]
On focus change, add the message - "Don't give up champ !"

**Comment by SmrutiRanjan-L** [comment]
Can I do this ?

**Comment by kaal-coder** [comment]
Yeah, you can. You can also add an emoji in the message if you wish too !

**Comment by SmrutiRanjan-L** [comment]
Okay Sure!!

**Comment by kaal-coder** [comment]
@SmrutiRanjan-L Improve the css file too.
If possible add gradient colors.

**Comment by SmrutiRanjan-L** [comment]
Yaa sure..

**Comment by kaal-coder** [comment]
Well done... It is as expected.
