### ISSUE TITLE
Adding spaces between username, save , pause and resume

### ISSUE THREAD

**Issue by Akash7649** [CareerDevelopmentHub/Sudoku-Solver#15]
I would like to add spaces between the username, save , pause and resume for better UI, so please assign me this issue under hacktoberfest 

![image](https://user-images.githubusercontent.com/101036630/196455480-64b5d7d7-7c05-4d5a-8ea2-08cd618c29e9.png)

**Comment by kaal-coder** [comment]
@Akash7649 go ahead !

**Comment by kaal-coder** [comment]
Great work @Akash7649 !
