### ISSUE TITLE
Save the game and resume option.

### ISSUE THREAD

**Issue by kaal-coder** [CareerDevelopmentHub/Sudoku-Solver#6]
When the user closes the game, he will be asked whether he wants to save or not.
When the website reopens, he will be asked whether he wants to resume or not.
Note:- The stopwatch will stop when closed and resume when reopened.

**Comment by Nevish-302** [comment]
can you assign this to me?

**Comment by kaal-coder** [comment]
Yeah sure. Send a preview of changes you made before making a PR.

**Comment by Nevish-302** [comment]
Where should I put the resume button?

**Comment by kaal-coder** [comment]
Near the Start new game or any desirable place you wish to.

**Comment by Nevish-302** [comment]
i have made the resume option but am facing issues while implementing the save the game while beforeunload event. The alert, confirm and prompt art ignored/blocked during this event but this event is applicable here.
Any suggestions???
or i can add save as a button too?

**Comment by Nevish-302** [comment]
![image](https://user-images.githubusercontent.com/62387252/195851370-8f94e9eb-2042-41ef-a31c-1a7b74f2aeae.png)
this is the problem...

**Comment by kaal-coder** [comment]
@Nevish-302 you can give the user a **save and close** button. After clicking it, the game will be saved.
The resume will happen when revisiting the site.

**Comment by Nevish-302** [comment]
okay

**Comment by Nevish-302** [comment]
i've accomplished saving  and resuming the original question. but even after responding or entering values to the box, the values are not getting changed in the board variable. i'd like to ask where is the user's data is saved when he attempts the question. i'm having trouble finding it. Any comments???

**Comment by Nevish-302** [comment]
here are the changes i've done.
the page looks like this now... 
![image](https://user-images.githubusercontent.com/62387252/195905596-88a19e83-7d3b-44cc-b092-1fa89eb542d6.png)

and it has the functionality of resume and save

**Comment by Nevish-302** [comment]
should i submit a pr?

**Comment by kaal-coder** [comment]
If possible increase the length where one can type username. In my system, it is very small.

Also the stopwatch doesn't resume, if possible have a look on it.

**Comment by kaal-coder** [comment]
If possible increase the length where one can type username. In my system, it is very small.

Also the stopwatch doesn't resume, if possible have a look on it.

**Comment by kaal-coder** [comment]
If possible increase the length where one can type username. In my system, it is very small.

Also the stopwatch doesn't resume, if possible have a look on it.

**Comment by Nevish-302** [comment]
I've changed it accordingly , have a look at it.

**Comment by kaal-coder** [comment]
Great one @Nevish-302 . Make a PR !
